### ISSUE TITLE
Postlara Yorum Yapılabilmesinin Sağlanması

### ISSUE THREAD

**Issue by alpemreelmas** [gelecekbilimde/backend#119]
Yazının Yorumları
    - Her kullanıcı yorum yapabilecektir ancak yorum yanıtlama mekanizması yoktur.
    - Kullanıcı diğer yorumları görebilecektir. Diğer yorumları görürken aşağıdaki özellikleri içerdiği şekilde görecektir.
        - Kişinin fotoğrafı
        - Kişinin Adı Soyadı
        - Yorum
    - Kullanıcı kendi yorumunu editleyebilir veya silebilir.
    - Admin tüm yorumlar üzerinde silme yetkisine sahiptir.

**Comment by aleyna-yildizli** [comment]
Bu taskta ilerleme kaydedilmediği için bu hafta elinden alınacaktır. @skarakasoglu

**Comment by aleyna-yildizli** [comment]
Bu task daha önce Süleyman’a atanmıştı, ancak son 1 ayda herhangi bir ilerleme olmadığı için bu görevi @MenekseYuncu 'ye devrettik. Eğer yardıma ihtiyacın olursa, lütfen bana ya da ekibe ulaşmaktan çekinme. Kolay gelsin.

**Comment by MenekseYuncu** [comment]
Comment yapısını hangi package  altına yazmam gerekiyor ?

**Comment by aleyna-yildizli** [comment]
post paketi içinde comment entity'si var o'dur sanırım @MenekseYuncu

**Comment by MenekseYuncu** [comment]
@aleyna-yildizli  tamamdır teşekkür ederim o zaman post paketi içerisinde endpointini de oluşturuyorum

**Comment by Ciklamert** [comment]
Mimari videosunda da anlatıldığı gibi aslında her şey ilgili olduğu paketin altında, yorum aslında postComment mantığında like ile post ilişkisi gibi bir ilişkiye sahip olduğu için postun altına yazabilirsin.

**Comment by agitrubard** [comment]
#127 yapılmadan bu issue yapılamayacağı için blocked olarak işaretlendi.
