### ISSUE TITLE
Mevcut postman collection'ını kullanarak durum tespiti

### ISSUE THREAD

**Issue by alpemreelmas** [gelecekbilimde/backend#120]
#### Yapılacaklar:

1. **Mevcut Postman Collection'ının İncelenmesi**:
   - Test edilmesi gereken endpoint'lerin mevcut Postman collection'ında yer alıp almadığının kontrol edilmesi.
   - Endpoint'lerin gerekli parametreler, body, header ve diğer ayarlarla doğru şekilde tanımlanıp tanımlanmadığının doğrulanması.

2. **Test Senaryolarının Belirlenmesi**:
   - Hangi endpoint'lerin test edileceği ve her bir endpoint için hangi test senaryolarının uygulanacağı belirlenmeli (örneğin, başarılı istek, hatalı istek, yetkilendirme hataları vb.).
   - Test senaryolarında kullanılacak giriş verileri (input) ve beklenen çıkış verilerinin (output) belirlenmesi.

3. **Postman Collection Güncellemeleri**:
   - Eksik olan test senaryoları veya endpoint'ler varsa, Postman collection'ına eklenmesi.
   - Mevcut testlerin doğruluğunu ve güncelliğini sağlamak için collection'ın gözden geçirilmesi ve gerekiyorsa güncellenmesi.

4. **Testlerin Çalıştırılması**:
   - Mevcut Postman collection'ındaki testler çalıştırılacak.
   - Testlerin başarılı olup olmadığının kontrol edilmesi ve başarısız olan testler için hata detaylarının kaydedilmesi.
   - Test sonuçlarının düzenli bir şekilde raporlanması (örneğin, başarısız testlerin nedenleri, hata mesajları, eksik veya hatalı endpoint'ler).

5. **Durum Tespiti ve Raporlama**:
   - Çalıştırılan test sonuçlarına dayanarak sistemin mevcut durumunun değerlendirilmesi.
   - Endpoint'lerdeki olası sorunlar, eksiklikler veya iyileştirme alanları hakkında bir durum tespiti raporu hazırlanması.
   - Test sonuçları doğrultusunda alınması gereken aksiyonların (örneğin, hatalı endpoint'lerin düzeltilmesi, eksik testlerin eklenmesi) belirlenmesi ve önerilmesi.

6. **Son Kontrol ve Geri Bildirim**:
   - Durum tespiti sonucunda alınacak aksiyonlar uygulanıp uygulanmadığının son bir kez kontrol edilmesi.
   - Geliştiricilere ve ilgili ekiplere geri bildirim sağlanması, gerektiğinde Postman collection'ının son halinin paylaşılması.

**Comment by aleyna-yildizli** [comment]
Bu hafta da görevde hiç güncelleme yok, ilerleme kaydettin mi yoksa bir blokaj mı var?  @MerveSoftware

**Comment by MerveSoftware** [comment]
Evet ilerleme kaydettim birkaç yerde 403 alıyorum tokeni validate etmemi
istiyor.
Bunun dışında bir iki güne tamamlarım hocam.

**Comment by aleyna-yildizli** [comment]
Merhaba @MerveSoftware,

birkaç gün içerisinde taskı tamamlayacağını belirtmiştin, ancak üzerinden 3 gün geçti. İlerlemeyle ilgili bir güncelleme bekliyoruz.

**Comment by MerveSoftware** [comment]
Mevcut postman collectionda  bazı yerlerde bu hatayı alıyorum "There was an error in evaluating the Pre-request Script:Error: Cannot read properties of undefined (reading 'json')" onun dişinda diger entpointler duzenli olarak calısıyor

**Comment by aleyna-yildizli** [comment]
Genel bir geri dönüş yapman faydalı olmuş eline sağlık ama detaylara biraz daha odaklanabilir misin?

Hangi endpointler sorunsuz çalışıyor? Hangi endpointlerde sorun yaşadın? Aldığın hatalarla birlikte yaptığın analizi dökümantasyon halinde sunabilir misin?

**Comment by MerveSoftware** [comment]
Şuan tespit ettiğim kadarıyla Non-Public APIs altinda olan entpoinlerde bu hatayı alıyorum.
entpointlerin içinde belirli bir json dosyası bulunmuyor . Buna benzer durumu birkaç kişi daha yaşamiş olmali arastırıyorum , https://community.postman.com/t/getting-error-in-evaluating-the-pre-request-script/43618

**Comment by aleyna-yildizli** [comment]
@MerveSoftware çalışmanı günceller misin lütfen?

Görevin durumunu güncellememe(hala readyde) ve labellerı değiştirmeme gibi durumlar, projenin akışını ve takımın iş takibini olumsuz etkileyebiliyor bu konuda daha dikkatli olalım.

**Comment by MerveSoftware** [comment]
Çalışmayı güncelledim backend tarafında hata veriyor gibi break point koyup postman tarafında send yapınca koda atıyor beni.
Önceki aldığım hata kaynağını tespit ettim şimdi test amaçlı bir deneme yapıyorum ve 403 döndü

**Comment by MerveSoftware** [comment]
Postmanda non-public APIs kısımda bulunanlar scriptte test olan kısımlar değiştirildi.
(error, result) => {
    pm.environment.set("ACCESS_TOKEN", result.json().test.accessToken)
    pm.environment.set("REFRESH_TOKEN", result.json().test.refreshToken)
    console.log(result.json())
    return
});

(error, result) => {
    pm.environment.set("ACCESS_TOKEN", result.json().content.accessToken)
    pm.environment.set("REFRESH_TOKEN", result.json().content.refreshToken)
    console.log(result.json())
    return
});

Content olarak değişince admin/post/{id} 
200 döndü 

Diğer kısımlar 403 , 405 ve bad request dönüyor

**Comment by MerveSoftware** [comment]
PubliC API postman entpoint test 
[Uploading Untitled 1.pdf…]()

**Comment by aleyna-yildizli** [comment]
@MerveSoftware,  taskı tamamladığını düşünüyorsan status ve labelı günceller misin? şu an hala In Progress olarak duruyor. Taskı ‘Review’ aşamasına geçirirsen ilerleyebiliriz. Eline sağlık. 👌🎊

**Comment by MerveSoftware** [comment]
Teşekkür ederim non public Api kısmı kaldı bitmek üzere birazdan onunda dokümanını eklemiş olacağım hocam.
Ardından hemen düzenleyeceğim.

**Comment by MerveSoftware** [comment]
NON-PUBLİC API DOKUMANI HAZIRLANDI
[Uploading nonpublicAPI.pdf…]()

**Comment by alpemreelmas** [comment]
> NON-PUBLİC API DOKUMANI HAZIRLANDI Uploading nonpublicAPI.pdf…

Tavsiyem, tüm dökümantasyonla alakalı yapılar github wiki üzerinden tutulmalı ki, dosyaların nerelerde olduğunu aramak zorunda kalmayalım aynı zamanda senin için de kolay olur çünkü her zaman en güncel halini paylaşmak zorunda kalmazsın.

**Comment by MerveSoftware** [comment]
girhub wiki dökümantasyonu hazırlandı @alpemreelmas
