### ISSUE TITLE
Rol Başvuruları ve Yönetim Servislerinin Yazılması

### ISSUE THREAD

**Issue by alpemreelmas** [gelecekbilimde/backend#121]
Gereksinim Metni Linkleri

https://github.com/gelecekbilimde/product/wiki/Faz-1-%7C-%C4%B0%C3%A7erik-Sayfas%C4%B1#kullan%C4%B1c%C4%B1-rolleri

https://github.com/gelecekbilimde/product/wiki/Faz-1-%7C-%C4%B0%C3%A7erik-Sayfas%C4%B1#kullan%C4%B1c%C4%B1-rolleri-ile-i%CC%87lgili-ek-a%C3%A7%C4%B1klamalar

https://github.com/gele[cekbilimde/product/wiki/Faz-1-%7C-%C4%B0%C3%A7erik-Sayfas%C4%B1#kullan%C4%B1c%C4%B1-rol-i%CC%87ste%C4%9Fi-g%C3%B6nderme-sayfas%C4%B1

https://github.com/gelecekbilimde/product/wiki/Faz-1-%7C-Y%C3%B6netim-Paneli (2.3.3)

Kullanıcı Rolleri
Platformda dört farklı kullanıcı rolü bulunmaktadır:

User (Kullanıcı)

Sisteme giriş yapabilir.
Paylaşılan yazıları okuyabilir, beğenebilir ve yorum yapabilir.
Diğer kullanıcıları takip edebilir ve kendisini takip edenleri görebilir.
Kendi profilini düzenleyebilir.
Author (Yazar)

User rolündeki tüm yetkilere ek olarak:
Yazı paylaşabilir.
Kendi yazılarını düzenleyebilir.
Moderator (Moderatör)

Author rolündeki tüm yetkilere ek olarak:
Tüm yazarların yazılarını gözden geçirebilir ve geri bildirim verebilir.
Yazıları düzenleyebilir ve yayınlanması için onaylayabilir ya da reddedebilir.
Admin (Yönetici)

Tüm sistem yetkilerine sahiptir.
Tüm kısımlar üzerinde CRUD (Oluşturma, Okuma, Güncelleme, Silme) işlemleri gerçekleştirebilir.
Kullanıcı rollerini doğrudan değiştirebilir (yazar, moderatör yapabilir).
Kullanıcı rol isteklerini onaylayabilir.
Kullanıcı Rol İsteği Gönderme Sayfası
Kullanıcılar, mevcut rolleri ile ilgili değişiklik taleplerini kolaylıkla yapabilirler:

İstek Gönderme Süreci Kullanıcının rol değişikliği isteği göndermesi için, sağ üstte bulunan profil ikonuna tıkladığında açılacak dropdown menüde "Rol Değişikliği İsteklerim" sekmesi bulunacaktır. Bu sekmeye tıklandığında aşağıdaki durum gerçekleşecektir.

Eğer bir kullanıcı User rolündeyse, "Yazar Ol" butonunu görecektir.
Eğer bir kullanıcı Author rolündeyse, "Moderatör Ol" butonunu görecektir. Butona Tıklama: Kullanıcı, uygun butona tıkladığında bir onay pop-up’ı belirecektir. Bu pop-up’da şu metin yer alacaktır:
"(Rol Adı) isteği göndermek istediğinize emin misiniz? Yazı yazma süreci hakkında daha fazla bilgi için [buraya](https://gelecekbilimde.net/sitemizde-bir-yazi-nasil-yayimlaniyor/) tıklayınız."

İstekleri Listeleme Modülü

İstek gönderdikten sonra bu sekmede, rol isteğinin durumu aşağıdaki statülerle görüntülenecektir:

İnceleniyor (In Review)

Reddedildi (Rejected)

Onaylandı (Approved)

İptal Edildi (Cancelled)

Bu sekmede rol isteği, durumu ve gönderildiği tarih gözükmesi yeterlidir.

Sayfanın alt kısmında şu metin yer alacaktır:

"Eğer isteğiniz hakkında detaylı bilgi edinmek istiyorsanız, [yazi.isleri@gelecekbilimde.net](mailto:yazi.isleri@gelecekbilimde.net) adresi ile iletişime geçiniz."
İstek Durumu Yönetimi
Eğer kullanıcının gönderdiği bir istek varsa, "İstekleriniz" başlığı altında rol adı, durumu ve isteğin gönderilme tarihi gösterilecektir. Kullanıcı, eğer isteği reddedildiyse aynı isteği tekrar gönderebilir.
Kullanıcı değerlendirme sürecinde olan isteğini geri çekmek amacıyla iptal edebilir.
Kullanıcı, "İstekleriniz" başlığı altında, gönderdiği rol taleplerini tarih sıralı olarak görecektir. En son gönderilen istek en üstte yer alacaktır.
Eğer kullanıcının mevcut bir rol isteği yoksa, şu uyarı mesajı görüntülenecektir:
"Mevcut olarak gönderdiğiniz bir rol isteği bulunmamaktadır."

2.3.3. Rol ve Yetki Yönetimi Ekranı(Admin İçin)

Admin, rol değişikliği talebinde bulunan kullanıcıları bir liste halinde görebilir. Liste; ad-soyad, e-mail, mevcut rol ve talep edilen rol gibi bilgileri içerir. Her isteğin yanında onayla ve reddet butonları bulunur. Aynı zamanda admin burada kullanıcıların profil detay sayfasına gidebilmelidir.

Ek özellik: Onay Bekleyenler(Varsayılan), Onaylananlar, Reddedilenler olarak filtreleme yapılabilmeli.

İstekler gönderilme tarihlerine göre sıralanmış şekilde gözükmeli.

**Comment by Ciklamert** [comment]
Rol mekanizmasında 5 rol olacak şekilde düzenlenmesi gerek diye isterlerde konuşmuştuk. Bu roller Admin, Moderator, Author, User, Guesttir. Admin rolüne geçiş işleminin aynısı moderatör rolü için de olmalı. Endpointlerdeki rollere göre access mekanizması da düzenlenmelidir (HasAnyAuthority() mekanizması)

**Comment by alpemreelmas** [comment]
> Rol mekanizmasında 5 rol olacak şekilde düzenlenmesi gerek diye isterlerde konuşmuştuk. Bu roller Admin, Moderator, Author, User, Guesttir. Admin rolüne geçiş işleminin aynısı moderatör rolü için de olmalı. Endpointlerdeki rollere göre access mekanizması da düzenlenmelidir (HasAnyAuthority() mekanizması)

O zaman şöyle yapalım siz isterlerin olduğu bir konuşmayı veyahut böyle bir dosya varsa hazırayıp bize iletir misiniz ? Bu şekilde görev dağılımı ve tanımı çok daha rahat olacaktır.

**Comment by Ciklamert** [comment]
İssuelarda rol mekanizması kısmında 5 rolün olduğu yazıyor. @aleyna-yildizli ile konuşmuştuk. İlgili issue'yu altta bırakıyorum.

https://github.com/gelecekbilimde/gelecekbilimde-backend/issues/96

Not: Rol mekanizması diye ayriyetten de belirtmiştik Aleyna ile ama şu an onu bulamadım. Burada Userlarla ilgili genel durum anlatılıyor.

**Comment by Ciklamert** [comment]
İssuelarda detayı var tüm isterlerin. @aleyna-yildizli  ile 2 saatlik bir toplantı sonucunda düzenlemiştik. Detayları Aleyna biliyor, duruma göre ek bir toplantı veya döküman düzenleyebiliriz.

**Comment by Ciklamert** [comment]
@alpemreelmas @agitrubard @meminkecik ## **Kullanıcı Rolleri**

Sistemde 4 farklı kullanıcı rolü olacaktır:

- **User**:
    - Sisteme giriş yapabilir.
    - Paylaşılan yazıları okuyabilir, beğenebilir, yorum yapabilir.
    - Diğer kullanıcıları takip edebilir ve kendisini takip edenleri görebilir.
    - Kendi profilini düzenleyebilir.
- **Author (Yazar)**:
    - **User** rolündeki yetkilere ek olarak aşağıdaki yetkilere sahiptir.
    - Yazı paylaşabilir.
    - Kendi yazılarını düzenleyebilir.
- **Moderator (Moderatör)**:
    - **Author** rolündeki yetkilere ek olarak aşağıdaki yetkilere sahiptir.
    - Tüm yazarların yazılarını gözden geçirebilir, geri bildirim verebilir.
    - Yazıları düzenleyebilir ve yayınlanması için onay verebilir ya da reddedebilir.
- **Admin**:
    - Sistemdeki tüm yetkilere sahiptir.
    - Kullanıcı rollerini değiştirebilir (Yazar, Moderatör yapabilir).

### **Kullanıcı Rolleri ile İlgili Ek Açıklamalar**

- Giriş yapmamış kullanıcılar sadece yazıları okuyabilir.
- Kullanıcılar yazar olmak için başvuruda bulunabilir. Bu isteği **Admin** inceleyip onaylayabilir.
- Yazarlar, moderatör olmak için başvuruda bulunabilir. **Admin** uygun görürse, kişinin profilini inceleyip moderatör yapabilir.
- Sisteme kaydolan her kullanıcıya ilk verilen rol User’dır.
- Yazar olma ve moderatör olma istekleri frontendde role göre gözüküp bir buton ile halledilebilir.

**Comment by aleyna-yildizli** [comment]
[Kullanıcı Rol İsteği Gönderme Sayfası](https://github.com/gelecekbilimde/gelecekbilimde-backend/wiki/Gereksinimler#kullanıcı-rolleri-ile-i%CC%87lgili-ek-açıklamalar-kullanıcı-rol-isteği-gönderme-sayfası) 'nın güncel halini inceler misin? @meminkecik

**Comment by aleyna-yildizli** [comment]
Bu hafta görevde hiç güncelleme yok, ilerleme kaydettin mi yoksa hala bir blokaj mı var? @meminkecik

**Comment by meminkecik** [comment]
> Bu hafta görevde hiç güncelleme yok, ilerleme kaydettin mi yoksa hala bir blokaj mı var? @meminkecik 

Henüz bir ilerleme kaydetmedim. Yoğunluğumdan dolayı bakamadım.

**Comment by agitrubard** [comment]
@meminkecik selamlar,
@alpemreelmas post kısmının teknik ve veri modeli analiziyle ilgileneceği için, issue'ya ben destek olacam. Muhtemelen 1-2 içerisinde bütün her şeyi tamamlayıp ilerletirim. Son durumda assignee kısmını da güncelliyorum.

**Comment by agitrubard** [comment]
> Kullanıcı rollerini değiştirebilir (Yazar, Moderatör yapabilir).

@aleyna-yildizli @Ciklamert cümlesini biraz daha açabilir miyiz? Başvuruları onaylamaktan mı, yoksa doğrudan değişiklik yapmaktan mı bahsediyoruz? Açıklamayı daha net olacak şekilde güncelleyebilirseniz süper olur.

**Comment by Ciklamert** [comment]
@agitrubard gereksinim metnini güncellendim. Açıklama metni eksik bırakılmış. Açıklamaya gereksinimdeki tüm detayları ekledim.

**Comment by Ciklamert** [comment]
Ana dökümandan kopyala yapıştır yaptım zaten. Orası güncellendikten sonra burası güncellenmemiş zamanında

**Comment by agitrubard** [comment]
@Ciklamert
Aşağıdaki kısmı biraz daha detaylandırabilir miyiz?

> Kişi isteği gönderdikten sonra profil sekmesinin altında gözükecek rol değişikliği isteklerim sekmesinden rol değişikliğinin durumunu görebilecektir

- Gösterilmek istenen veri nedir?
- Nasıl bir ekran düşünülüyor?
- Başvurularım gibi bir kısımda mı olacak, yoksa inceleniyor gibi bir şey mi yazacak?
- Başvuru olmadığında bu kısım olmayacak mı? UI tarafı Back-End'e hangi durumlarda soracak?
- Başvuru yok ise nasıl bir yazı gösterilecek?
- Başvuru İnceleniyor değilse, `Approved` veya `Rejected` ise uygulama nasıl davranacak?

Burayı netleştirebilirsek ona göre endpointlerin sayısı ve özellikleri değişebilir.

**Comment by Ciklamert** [comment]
Gereksinim sayfa hakkında detaylı bilgi ile güncellenmiştir. @agitrubard

**Comment by agitrubard** [comment]
@Ciklamert eline sağlık 🙌🏼 

Yarın inceleyecem. Ekstra bir şey olursa haberleşiriz tekrar.

**Comment by agitrubard** [comment]
@Ciklamert `is_hidden` alanı `gb_role` tablosunda var fakat kullanım amacını göremedim. Bu alanı kaldıralım mı? Çünkü gizlememizi gerektiren bir durum yok gibi duruyor.

**Comment by agitrubard** [comment]
@Ciklamert ek olarak aşağıdaki kısımda silme hakkı dediğimiz şey sistemden tamamen silmeden mi bahsediyoruz? Yoksa sistemde var olacak fakat silindi olarak mı görünecek?
> Ayrıca, kabul edilen, reddedilen veya onaylanan isteklerini silme hakkına sahiptir.

**Comment by Ciklamert** [comment]
@agitrubard is_hidden seçeneğinde şu anlamda kullanabiliriz belki. Kullanıcı kendi ekranından sildiğinde kullanıcıya gözükmesin ama admin panelinden biz daha önce başvurup/başvurmadığını görebilelim yani admine gözükecek şekilde olsun. is_hidden gönderen kullanıcı için silinip silinmediğini kontrol eden bir değişken olabilir. Müsait olunca gereksinim maddesini düzenleyecem. Şimdilik bu şekilde güncelleyebilirsin.

**Comment by agitrubard** [comment]
@Ciklamert `is_hidden` alanı `gb_role` tablosunda `gb_role_application` tarafında değil. Benim sorduğum rol içindi. Yani rolü gizlemek veya gizlememek içindi. Eğer başvuruları sadece kullanıcı kendi tarafından silindiğini görecekse ve bu panelde görünecekse buraya farklı bir yapı kurmamız gerekiyor. Bu kısımları netleştirebilirsek süper olur çünkü hem geliştirmeyi uzatıyor hem de yavaşlatıyor. Hatta bence silme konusunu eklemiyor olmamız daha sağlıklı. Bunun yerine başvuru sonuçlandırılmamışsa yani onaylanmamış veya reddedilmemişse kullanıcının iptal etmesini sağlyabiliriz. Bu sayede başvuru iptal edildi statüsünde olur. Zaten kullanıcı kendi başvurusunu reddedeceği için bir sorun oluşmaz diye düşünüyorum.

**Comment by Ciklamert** [comment]
Aslında orada kastım iptal etmekten ziyade kullanıcı eğer 2-3 defa başvurdu ise başvurularım listesinde sadece son başvuruyu görmek istiyorsa kendine gözüken listeden silebilsin şeklindeydi. Bunun üzerine bir kafa yorup bu akşam düzenleyeyim

**Comment by Ciklamert** [comment]
@agitrubard @aleyna-yildizli tekrar düşünme sonucu silme özelliği yerine tarih olarak en son gönderilen isteğin en yukarıda gözükeceği bir sistem ve iptal etme mekanizması koymak daha mantıklı geldi. O şekilde olacak şekilde güncelledim.

**Comment by agitrubard** [comment]
@Ciklamert tamamdır eline emeğine sağlık 🙌🏼

**Comment by agitrubard** [comment]
@Ciklamert 
Aşağıdaki kısım sıralanmış deniliyor ama hangi sırada sıralanacağı belirtilmemiş. Bunu düzenleyebilir miyiz?

> İstekler gönderilme tarihlerine göre sıralanmış şekilde gözükmeli.

**Comment by Ciklamert** [comment]
Kişinin kendi başvuruları için olduğu gibi admin tarafında da en son gönderilen tarihler ekranda en yukarıda gözükecek şekilde sıralanmalı.

**Comment by agitrubard** [comment]
@Ciklamert burayı dinamik yapalım zaten alt yapımız buna izin veriyor. Ön yüz nasıl gönderirse öyle sıralansın ✅


Aşağıdaki kısım iki ekran için de mi geçerli? Ek özellik gibi ayrıca yazıldığı için sormak istedim;
> Ek özellik: Onay Bekleyenler(Varsayılan), Onaylananlar, Reddedilenler olarak filtreleme yapılabilmeli.

**Comment by Ciklamert** [comment]
Evet @agitrubard
