### ISSUE TITLE
Wordpress ve Yeni Post Tablolarının Analiz Edilmesi

### ISSUE THREAD

**Issue by Ciklamert** [gelecekbilimde/backend#127]
Wordpress üzerinde çalışan mevcut sitemizin post tablosu ile yeni veritabanımızdaki post tablosu karşılaştırılacak. Hangi sütunların hangi sütunlara denk geldiği belirlenecek ve eksik sütun varsa yazılacaktır. Sadece dökümantasyon yapılması yeterlidir. 
Görevi alan kişiye ilgili yetki ve anlatımı ben yapacağım. Görevi alan kişi benle iletişim kurabilir.

**Comment by agitrubard** [comment]
@Ciklamert dün konuştuğumuz konuları buraya açıklama olarak ekleyebilir miyiz?

**Comment by agitrubard** [comment]
@Ciklamert bu konu ele alınacak mı? Post kısmının tasarlanabilmesi ve geliştirilebilmesi için buradaki analizin tamamlanması gerekiyor. Bir çok konudan daha öncelikli

**Comment by Ciklamert** [comment]
@alpemreelmas 'a veritabanı bilgilerini iletmiştim, geçen hafta erişimle ilgili bir sorun yaşamıştı ama bu hafta çözmüştük onu ve bakacağını söylemişti.
@alpemreelmas  bu issue ne durumda? Bakacak mısın?

**Comment by alpemreelmas** [comment]
> @alpemreelmas 'a veritabanı bilgilerini iletmiştim, geçen hafta erişimle ilgili bir sorun yaşamıştı ama bu hafta çözmüştük onu ve bakacağını söylemişti.
> @alpemreelmas  bu issue ne durumda? Bakacak mısın?

Evet bakacağım ancak, 2 günden önce teslim edemem eğer acilen gerekliyse todoyu başkasına assign edebilirsiniz
En erken çarşamba teslim edebilirim.

**Comment by Ciklamert** [comment]
Bu hafta içinde bakamazsan başkasına veririz. Sorun yok 👍

**Comment by alpemreelmas** [comment]
Bu sadece wp'in post tablosu ile yeni sistemin post tablosu karşılaştırılması ve dokümantasyonu değil mi ? Diğer tabloların analizi istenmiyor değil mi ? @Ciklamert @aleyna-yildizli

**Comment by Ciklamert** [comment]
Sadece post tablosu olması yeterlidir ancak postların author gibi bilgilerini bulurken user tablosu ile vb. join yapman gerekebilir. Dolayısıyla postta id'si bulunan diğer tablolara da ufak bir göz atarsan, analiz açısından daha faydalı olabilir.

**Comment by alpemreelmas** [comment]
https://github.com/gelecekbilimde/product/wiki/Wordpress-Database-Post-Tablosu-Veri-Analizi

çalışmayı burdan takip edebilirsiniz

**Comment by Ciklamert** [comment]
@alpemreelmas  wp-term-taxonomy ve post meta tablolarına bakarak oradaki ilişkilerine de bir bakabilir misin? Oralarda da kaynak ve kategori bilgileri vardı diye hatırlıyorum. Bu iki kısımla ilgili ilişkilerin olduğu tabloların da bulunması tabloları sağlıklı bir şekilde geçirebilmemiz için şarttır. Eğer kaynaklar postmetada değilse tielabs_meta adlı bir tema meta dosyası olmalı. Orada olabilir. Analizine bunları da eklerim. Postun kategori ve kaynak ilişkilerinin veritabanında nasıl halledildiğine bakabilir misin? Eğer bir sorun yaşarsan birlikte de bakabiliriz.
