### ISSUE TITLE
Code Rabbit Entegrasyonu

### ISSUE THREAD

**Issue by alpemreelmas** [gelecekbilimde/backend#148]

**Comment by agitrubard** [comment]
@mert-ayhan ekibin coderabbit konusundaki fikrini alalım derim. En son yaptığı 60 yorum ile birlikte "bunların hepsini yapacak mıyız" gibi sorular geldi. Yetkinlik seviyesinin ve kemik kadronun oluşmasını beklemek iyi olabilir diye düşünüyorum. Ya da birinin önce Code Rabbit'i optimize etmesi gerekiyor ve o süreye kadar ilgili arkadaşların yorumları göz önüne almaması gerekiyor.

**Comment by agitrubard** [comment]
> @mert-ayhan ekibin coderabbit konusundaki fikrini alalım derim. En son yaptığı 60 yorum ile birlikte "bunların hepsini yapacak mıyız" gibi sorular geldi. Yetkinlik seviyesinin ve kemik kadronun oluşmasını beklemek iyi olabilir diye düşünüyorum. Ya da birinin önce Code Rabbit'i optimize etmesi gerekiyor ve o süreye kadar ilgili arkadaşların yorumları göz önüne almaması gerekiyor.

@mert-ayhan yaptığım yorum üzerine bir aksiyon alabilecek miyiz? Çok fazla yorum yapılıyor, tekrar dönüp yorumları okuması ve optimize edilmesi biraz zorlaşıyor. Optimize edebilirsek kullanabiliriz gibi düşünüyorum ama birinin sadece oradaki yorumlara bunu önerme gibi bir yapıya dönmesi gerekiyor. Pull Request açanlar hangilerini yapacaklarını bilemeyebiliyorlar.
