### ISSUE TITLE
SonarQube Entegrasyonu

### ISSUE THREAD

**Issue by alpemreelmas** [gelecekbilimde/backend#149]

**Comment by agitrubard** [comment]
@Ciklamert bu issue yapılmıyor neden `in progress` olarak işaretledik?

**Comment by Ciklamert** [comment]
@mert-ayhan  tarafından sonarqube entegrasyonu eklendi organizasyona, bunla ilgili geçmişte de bir geliştirme yapılmıştı. O yüzden labelları düzenlerken bu şekilde bir işaretleme yapmıştım. Eğer bir geliştirme yoksa label'ı kaldırabiliriz.
