### ISSUE TITLE
Test Alt Yapısının Oluşturulması

### ISSUE THREAD

**Issue by alpemreelmas** [gelecekbilimde/backend#153]

**Comment by agitrubard** [comment]
@alpemreelmas şu aşamada test yazılmasını önermiyorum. Çalışmayan, tablosu olmayan bir sürü endpoint var. Önce bunları ortaya koyup ilerlememiz gerekiyor ki UI tarafı entegre olabilsin. Daha sonra dönüp testleri yazabiliriz. Baştan yapılmadığı için çok zaman kaybedilebilir ve değişebilir 👍🏼
