### ISSUE TITLE
Admin/Moderatör - Kullanıcı Profil Bilgileri Detay Ekranı Geliştirilmesi 1

### ISSUE THREAD

**Issue by aleyna-yildizli** [gelecekbilimde/backend#162]
Admin ve moderatörler için kullanıcının tüm profil bilgilerini, varsa tüm rol istekleri; durumları, gönderildikleri tarih ile görüntüleyen bir ekran geliştirilmesi gerekmektedir. Kullanıcı listeleme ekranındaki detay butonuna tıklandığında açılacak olan bu ekran, aşağıdaki bilgileri içerecektir:

Kullanıcının Profil Bilgileri:
 • Kullanıcının adı, soyadı, e-posta adresi, eğitim seviyesi, doğum tarihi gibi tüm bilgileri.
 • Kullanıcının rolü (Admin, Moderatör, Yazar, Kullanıcı).

Admin kullanıcının rol isteklerini yönetebilir. Ancak moderatörler rol isteği üzerinde yetki sahibi değildir; fakat rol isteklerini görüntüleyebilir bu duruma dikkat edilmelidir.

**Comment by aleyna-yildizli** [comment]
@zehrayhn bu task senin için uygun mu?

**Comment by zehrayhn** [comment]
Uygun benim için.

**Comment by zehrayhn** [comment]
Uygun benim için @aleyna-yildizli
